name: Update Repo B with Submodule

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Cloner Repo B
        run: |
          git clone https://github.com/TheotimChevalier/Repo-B.git
          cd Repo-B
          git submodule update --init --recursive || exit 1

      - name: Vérification des sous-modules
        run: |
          cd Repo-B
          git submodule status || echo "Sous-module non initialisé"

      - name: Créer ou utiliser une branche basée sur l'utilisateur
        run: |
          cd Repo-B
          git fetch origin
          BRANCH_NAME="update-${{ github.actor }}"
          if git rev-parse --verify origin/$BRANCH_NAME; then
            git checkout $BRANCH_NAME
          else
            git checkout -b $BRANCH_NAME
          fi

      - name: Mettre à jour le sous-module dans Repo B
        run: |
          cd Repo-B
          git submodule update --remote --merge || exit 1
          if git diff --quiet; then
            echo "Pas de modifications dans le sous-module"
          else
            git add .
            git commit -m "Update submodule Repo A by ${{ github.actor }}"
          fi

      - name: Push changes to Repo B
        run: |
          cd Repo-B
          git push origin $BRANCH_NAME || exit 1



2024-10-08 08:52:16.468 [warning] [Git][config] git config failed: Failed to execute git
2024-10-08 08:52:16.621 [info] > git reflog main --grep-reflog=branch: Created from *. [135ms]
2024-10-08 08:52:16.700 [warning] [Model][getRepositoryExact] Failed to get repository realpath for: "c:\Projets_QDS\CI_CD\RepoB\src". Error:Error: ENOENT: no such file or directory, realpath 'c:\Projets_QDS\CI_CD\RepoB\src'