on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  update-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Cloner Repo B
        run: |
          git clone https://github.com/TheotimChevalier/Repo-B.git
          cd Repo-B
          git submodule update --init --recursive

      - name: Créer ou utiliser une branche basée sur l'utilisateur
        run: |
          cd Repo-B
          BRANCH_NAME="update-${{ github.actor }}"
          # Crée une nouvelle branche si elle n'existe pas
          git fetch origin
          if git rev-parse --verify origin/$BRANCH_NAME; then
            git checkout $BRANCH_NAME
          else
            git checkout -b $BRANCH_NAME
          fi

      - name: Mettre à jour le sous-module dans Repo B
        run: |
          cd Repo-B
          git submodule update --remote --merge
          git add . 
          git commit -m "Update submodule Repo A by ${{ github.actor }}"

      - name: Push changes to Repo B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd Repo-B
          git push origin $BRANCH_NAME