name: Mise à jour du sous-module

on:
  push:
    paths:
      - 'path\to\C:\Projets_QDS\CI_CD\RepoA\*'
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions\/checkout@v3
        with:
          submodules: recursive

      - name: Mise à jour du sous-module
        run: |
          git submodule update --remote
          git add path\to\C:\Projets_QDS\CI_CD\RepoA  # Ajoute les modifications du sous-module
          git commit -m \"Mise à jour automatique du sous-module\"
          git push