name: Mise à jour du sous-module

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3
        with:
          submodules: recursive # Récupère les sous-modules

      - name: Configurer Git
        run: |
          git config user.name "TheotimChevalier"
          git config user.email "Theotimc.chevalier@free.fr"

      - name: Créer ou utiliser une branche basée sur l'utilisateur
        run: |
          BRANCH_NAME="update-${{ github.actor }}"
          git fetch origin
          # Crée une nouvelle branche s'il n'y en a pas
          if git rev-parse --verify origin/$BRANCH_NAME; then
            git checkout $BRANCH_NAME
          else
            git checkout -b $BRANCH_NAME
          fi

      - name: Mise à jour du sous-module
        run: |
          git submodule status
          git submodule update --remote --merge # Mettre à jour le sous-module
          git add .  # Ajoute les modifications locales du sous-module
          git commit -m "Mise à jour automatique du sous-module par ${{ github.actor }}"

      - name: Push des changements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/TheotimChevalier/Repo-B.git
          git push origin $BRANCH_NAME


