name: Mise à jour du sous-module

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt principal avec sous-modules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Configurer Git
        run: |
          echo "Configuration de Git"
          git config user.name "TheotimChevalier"
          git config user.email "Theotimc.chevalier@free.fr"

      - name: Vérification de l'état du sous-module
        run: |
          echo "Vérification de l'état du sous-module"
          git submodule status || { echo "Échec de la vérification de l'état du sous-module"; exit 1; }

      - name: Créer ou utiliser une branche basée sur l'utilisateur
        run: |
          echo "Création ou utilisation de la branche pour l'utilisateur"
          BRANCH_NAME="update-${{ github.actor }}"
          git fetch origin
          if git rev-parse --verify origin/$BRANCH_NAME; then
            git checkout $BRANCH_NAME
          else
            git checkout -b $BRANCH_NAME
          fi

      - name: Mise à jour du sous-module
        run: |
          echo "Mise à jour du sous-module"
          git submodule update --remote --merge || { echo "Échec de la mise à jour du sous-module"; exit 1; }
          if git diff --quiet; then
            echo "Pas de modifications dans le sous-module"
          else
            git add c:\Projets_QDS\CI_CD\RepoB
            git commit -m "Mise à jour automatique du sous-module par ${{ github.actor }}" || echo "Aucun changement à commettre"
          fi

      - name: Diagnostic Git avant push
        run: |
          echo "==== DIAGNOSTIC AVANT PUSH ===="
          git status
          git log -1
          git branch -r
          git remote -v

      - name: Push des changements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Pushing changes to remote repository"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/TheotimChevalier/Repo-B.git
          git push origin $BRANCH_NAME || { echo "Erreur lors du push"; exit 1; }