name: Mise à jour du sous-module

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt principal avec sous-modules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.workflows_token }}  
          fetch-depth: 0

      - name: Configurer Git
        run: |
          echo "Configuration de Git"
          git config user.name "TheotimChevalier"
          git config user.email "Theotimc.chevalier@free.fr"

      - name: Vérification de l'état du sous-module
        run: |
          echo "Vérification de l'état du sous-module"
          git submodule status 

      - name: Créer ou utiliser une branche basée sur l'utilisateur
        run: |
          echo "Création ou utilisation de la branche pour l'utilisateur"
          BRANCH_NAME="update-${{ github.actor }}"
          git fetch origin
          if git rev-parse --verify origin/$BRANCH_NAME; then
            git checkout $BRANCH_NAME
          else
            git checkout -b $BRANCH_NAME
          fi

      - name: Mise à jour du sous-module
        run: |
          echo "Mise à jour du sous-module"
          git submodule update --remote --merge 
          if git diff --quiet; then
            echo "Pas de modifications dans le sous-module"
          else
            git add .
            git commit -m "Mise à jour automatique du sous-module par ${{ github.actor }}" 
          fi

      - name: Diagnostic Git avant push
        run: |
          echo "==== DIAGNOSTIC AVANT PUSH ===="
          git status
          git log -1
          git branch -r
          git remote -v

      - name: Push des changements
        env:
         GITHUB_TOKEN: ${{ secrets.workflows_token }}  # Utilisez le même secret pour le push
        run: |
          echo "Pushing changes to remote repository"
          git remote set-url origin https://x-access-token:${{ secrets.workflows_token }}@github.com/TheotimChevalier/Repo-B.git
          git push origin $BRANCH_NAME 
