name: Submodule update

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of the main repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.WORKFLOWS_TOKEN }}  
          fetch-depth: 0

      - name: Configure Git
        run: |
          echo "Configuration of Git"
          git config user.name "TheotimChevalier"
          git config user.email "Theotimc.chevalier@free.fr"

      - name: Checking submodule status
        run: |
          echo "Checking submodule status"
          git submodule status 

      - name: Submodule update
        run: |
          echo "Submodule update"
          git submodule update --remote --merge 
          if git diff --quiet; then
            echo "No changes in submodule"
          else
            git add .
            git commit -m "Automatic submodule update" 
          fi

      - name: Pushing changes
        env:
          WORKFLOWS_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}  
        run: |
          echo "Pushing changes to remote repository"
          git remote set-url origin https://x-access-token:${{ secrets.WORKFLOWS_TOKEN }}@github.com/TheotimChevalier/Repo-B.git
          git push origin main 