name: Update Repo B on Change

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  update-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.WORKFLOWS_TOKEN }}  # Utilisation du token pour accéder à Repo A
          fetch-depth: 0

      - name: Configure Git
        run: |
          echo "Configuration de Git"
          git config user.name "TheotimChevalier"
          git config user.email "Theotimc.chevalier@free.fr"

      - name: Clone Repo B
        run: |
          echo "Clonage de Repo B avec sous-modules"
          git clone https://x-access-token:${{ secrets.WORKFLOWS_TOKEN }}@github.com/TheotimChevalier/Repo-B.git
          cd Repo-B
          # Configure l'URL du sous-module Repo A avec le token pour authentification
          git config submodule.apps/web/src.url https://x-access-token:${{ secrets.WORKFLOWS_TOKEN }}@github.com/TheotimChevalier/Repo-A.git
          git submodule update --init --recursive

      - name: Configure Git in Repo B
        run: |
          echo "Configuration de Git dans Repo B"
          cd Repo-B
          git config user.name "TheotimChevalier"
          git config user.email "Theotimc.chevalier@free.fr"

      - name: Update submodule in Repo B
        run: |
          cd Repo-B
          echo "Mise à jour du sous-module dans Repo B"
          git submodule update --remote --merge
          if git diff --quiet; then
            echo "Aucune modification dans le sous-module"
          else
            git add .
            git commit -m "Update submodule from Repo A"
          fi

      - name: Push changes to Repo B
        env:
          WORKFLOWS_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}  # Utilise le token pour pousser vers Repo B
        run: |
          cd Repo-B
          echo "Pousser les modifications vers Repo B"
          git push origin main