name: Mise à jour du sous-module

on:
  push:
    paths:
      - 'https://github.com/TheotimChevalier/Repo-A.git'
    workflow_dispatch:

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3
        with:
          submodules: recursive 
          # Cette étape permet de récupérer le code du repo B pour exécuter les actions suivantes 


      - name: Mise à jour du sous-module
        run: |
          git submodule update --remote # Mettre à jour le sous-module avec les dernières modifications
          git add https://github.com/TheotimChevalier/Repo-A.git  # Ajoute les modifications du sous-module
          git commit -m "Mise à jour automatique du sous-module" # Valide les changements
          git push